### ISSUE TITLE
About traffic data. 

### ISSUE THREAD

**Issue by HawkTom** [silaslobo/InTAS#2]
Hello,

May I ask where you get the real traffic data of the city, because I also want to build a real scenario for a city but I don't know how to get the real traffic data. 

Best,
Hao

**Comment by silaslobo** [comment]
Hi Hao,

For the development of InTAS, I got the data from Ingolstadt's traffic authorities. They made available the data from induction loops placed around the city, and using SUMO methodology the scenario has been created. You can take a look in what type of information you have and compare with the best SUMO's demand modeling (https://sumo.dlr.de/docs/Demand/Introduction_to_demand_modelling_in_SUMO.html)

Regards,
Silas

**Comment by silaslobo** [comment]
closing for no feed back from Mr. Hao
