### ISSUE TITLE
Not loading with SUMO 1.10.0

### ISSUE THREAD

**Issue by johschmitz** [silaslobo/InTAS#5]
I installed SUMO 1.10.0 from the ppa:
https://sumo.dlr.de/docs/Downloads.php#linux_binaries

However, when running

    sumo-gui -c InTAS_full_poly.sumocfg

It seems to get stuck during loading.

**Comment by johschmitz** [comment]
Okay, I think the issue can be closed. I found that it just took really long to load.
Even after saying

    Loading done.

one has to wait for several minutes. Not sure if the scenario can be updated to avoid this problem or if this is a general problem of the SUMO engine itself.

**Comment by silaslobo** [comment]
Hi Johannes,

I did not validate InTAS with SUMO 1.10 yet, but as soon as I validate I will write you a feedback here. It will be probably until the end of this week.
Btw. what are using as OS to run SUMO?

**Comment by johschmitz** [comment]
I am using Linux Mint 20.

**Comment by Delooz** [comment]
Hello @johschmitz, could you please send a screenshot of what happens when you execute the command you indicated?

**Comment by johschmitz** [comment]
Could do it after my holidays. Basically nothing special happens, loading
just takes very long. But maybe the model is very big and this is normal? I
just don't have enough SUMO experience basically. Maybe we should compare
load times and machine specs?

**Comment by Delooz** [comment]
What you are describing seems to be similar to something I already faced. Shortly, sumo is not well configured or missing files and tries everytime to download files from online, which takes few minutes.
Do you face the same issue with any other sumo scenario?
